accueil/urls.py
from django.urls import path
from . import views

app_name = 'accueil'

urlpatterns = [
    path('',views.accueil, name='accueil' ),
    path('success/' , views.send_success , name='send_success')
    
]

blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path('',views.post_list, name='post_list' ),
    path('<int:id>' , views.post_detail , name='post_detail'),
]

project/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns =[

    path('summernote/', include('django_summernote.urls')),
    path('admin/', admin.site.urls),
    path('blog/' , include('blog.urls' , namespace='blog')),
    path('contact/' , include('contact.urls' , namespace='contact')),
 
    path('services/' , include('services.urls' , namespace='services')),
    path('equipes/' , include('equipes.urls' , namespace='equipes')),
    path('' , include('accueil.urls' , namespace='accueil')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)  
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)



admin.site.site_header = "Cabinet_Dentaire AdminPanel"
admin.site.site_title = "Cabinet_Dentaire App Admin"
admin.site.site_index_title = "Bienvenue !!t"

accueil/models.py
from django.db import models
import datetime

TITLE_CHOICES = [
     ('consultation', 'Consultation'),
    ('soins dentaire urgents', 'Soins dentaire urgents'),
    
]

# Create your models here.
class Rend(models.Model):
    nom = models.CharField( max_length=40)
    courriel = models.EmailField( max_length=50)
    choix = models.CharField(max_length=100, default="non")
    téléphone = models.IntegerField(null=True)
    
    Raison = models.CharField(max_length=50, choices=TITLE_CHOICES, null=True)
    La_Date = models.DateField(("Date"), default=datetime.date.today)
    


    def __str__(self):
        return self.nom

accueil/forms.py
# Import form modules
from django import forms

from accueil.models import TITLE_CHOICES, Rend
from functools import partial

DateInput = partial(forms.DateInput, {'class': 'datepicker'})

CHOICES = [
 ('Oui', 'oui'),
 ('Non', 'non')
]


class DateInput(forms.DateInput):
    input_type = 'date'

# Create class to define the form fields
class RendForm(forms.ModelForm):
    nom = forms.CharField(label="nom complet", max_length=40)
    courriel = forms.EmailField(label="courriel", max_length=50)
    choix = forms.ChoiceField(label='Etes-vous déjà patient à notre cabinet?', choices=CHOICES)
    téléphone = forms.IntegerField()
    
    Raison = forms.ChoiceField(label='Raison de votre visite :', choices=TITLE_CHOICES)
    
  

    



    def __str__(self):
        return self.nom


    class Meta:
          model = Rend  
          fields = ['nom', 'courriel','choix','téléphone','Raison','La_Date']
          widgets = {
            'La_Date': DateInput(),
        }

accueil/views.py

from django.shortcuts import render , redirect
from accueil.forms import RendForm
from blog.models import Post
from services.models import Services
from equipes.models import Equipes
from django.core.mail import send_mail, BadHeaderError
from django.http import HttpResponse , HttpResponseRedirect


def accueil(request):
    # Check the form is submitted or not


   posts = Post.objects.all()
   services = Services.objects.all()
   service_list = Services.objects.all()
   posts = Post.objects.all()
   post_list = Post.objects.all()
   equipes = Equipes.objects.all()
   equipe_list = Equipes.objects.all()
   rendez_vous = RendForm()

   if request.method == 'POST' :
        rendez_vous = RendForm(request.POST, request.FILES)

        if rendez_vous.is_valid():

            

            nom = rendez_vous.cleaned_data['nom']
            courriel = rendez_vous.cleaned_data['courriel']
            choix = rendez_vous.cleaned_data['choix']
            
            
            
            


            
            rendez_vous.save()
            try : 
                send_mail(nom,choix,courriel,['admin@example.com'])

            except BadHeaderError:    
                return HttpResponse('ivalid header')
            return redirect('accueil:send_success')   

        else: 
          rendez_vous = RendForm()


   context = {  
                'form' : rendez_vous,
                'services' : services,
                'service_list' : service_list,
                'posts' : posts,
                'post_list' : post_list ,
                'equipes' : equipes,
                'equipe_list' : equipe_list ,
              }

   return render(request , 'accueil/index.html' , context)


def send_success(request):
    context = {
        'send_success' : send_success
    }
    return render(request , 'accueil/send_success.html' , context)
    


    



   

accueil/templates/accueil/send_success.html
{% extends 'base.html' %}

{% load static %}
{% load bootstrap4 %}

{% block body %}




<div class="full-screen black-overlay-70 vertical-center" style="background-image: url(/static/site_static/1.jpg);">
	<div class="container">
		<div class="row">
			<div class="col-md-10 col-sm-12 col-12 offset-md-1 center-holder">
				
				<div class="large-heading center-holder">
					<h5 class="white-color light ls-none opacity-04">Merci pour vous!</h5>
					<h3 class="white-color extra-light ls-none">Nous vous contacterons bientôt pour confirmer votre rendez-vous.</h3>
				</div>

				<div class="center-holder">
				<!-- Subscribe Modal Start -->
					<div class="mt-30">
						<a href="{% url 'accueil:accueil' %}" class="primary-button button-sm "  style="background-color:rgb(60,136,126); border:2px solid rgb(60,136,126);">
							retour à la page d'accueil</a>
						
						
							
						</div>		
						<!-- Modal End -->	
					</div>				
					<!-- Subscribe Modal End -->					
				</div>
			</div>
		</div>		
	</div>
</div>

<!-- Scroll to top button Start -->
<a href="#" class="scroll-to-top"><i class="fas fa-chevron-up"></i></a>	
<!-- Scroll to top button End -->

{% endblock body %}